# Generated by Django 3.0.7 on 2020-06-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(default='', max_length=200)),
                ('date1', models.DateField(null=True)),
                ('labels', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('priority', models.CharField(default='', max_length=10)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
