# Generated by Django 3.0.6 on 2020-06-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date1',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.CharField(default='Personal', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
